baseURL = 'https://www.openhippo.ai/'
languageCode = 'de-de'
title = 'Open Hippo - Wir bauen KI.'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Site configuration
[params]
  description = "Open Hippo – DSGVO‑ und EU-KI-Gesetz‑konforme KI‑Lösungen aus Deutschland"
  author = "Open Hippo"
  keywords = ["KI", "Künstliche Intelligenz", "DSGVO", "Deutschland", "API"]
  
# SEO and social media
[params.social]
  twitter_image = "/images/Logo-OpenHippo-f-rgb-p-2600.png"
  og_image = "/images/Logo-OpenHippo-f-rgb-p-2600.png"

# Navigation menu
[menu]
  [[menu.main]]
    name = "Produkte"
    identifier = "produkte"
    weight = 10
    
  [[menu.main]]
    name = "Hippo Token"
    url = "/produkte/token/"
    parent = "produkte"
    weight = 11
    
  [[menu.main]]
    name = "Hippo Chat"
    url = "/produkte/chat/"
    parent = "produkte"
    weight = 12
    
  [[menu.main]]
    name = "Dienste"
    identifier = "dienste"
    weight = 20
    
  [[menu.main]]
    name = "Beratung"
    url = "/dienste/beratung/"
    parent = "dienste"
    weight = 21
    
  [[menu.main]]
    name = "On-Prem"
    url = "/dienste/onprem/"
    parent = "dienste"
    weight = 22
    
  [[menu.main]]
    name = "Beispiele"
    identifier = "beispiele"
    weight = 30
    
  [[menu.main]]
    name = "Schatten-KI"
    url = "/beispiele/schatten-ki/"
    parent = "beispiele"
    weight = 32
    
  [[menu.main]]
    name = "KI-Souveränität"
    url = "/beispiele/ki-souveraenitaet/"
    parent = "beispiele"
    weight = 31

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
